"""REB static re-entry fixtures — gap bands and adversarial cases."""

from __future__ import annotations

from typing import Any

from hg_runtime.reentry_boundary.types import (
    FIXTURE_CLOCK,
    discontinuity_from_fixture,
    reentry_request_from_fixture,
)

FIXTURE_REENTRY_BUNDLES: tuple[dict[str, Any], ...] = (
    {
        "bundle_id": "reb-gap-1-hour",
        "discontinuity": {
            "discontinuity_event_id": "reb-disc-1h",
            "agent_ref": "agent:0",
            "discontinuity_type": "pause",
            "started_at": "2026-06-14T15:00:00.000000Z",
            "ended_at": FIXTURE_CLOCK,
            "duration_estimate": "PT1800S",
            "evidence_refs": ("ev:pause-1h",),
        },
        "reentry_request": {
            "reentry_request_id": "reb-req-1h",
            "agent_ref": "agent:0",
            "discontinuity_event_ref": "reb:reb-disc-1h",
            "requested_reentry_mode": "observe_only",
            "requested_scope": "resume local observation after short pause",
            "evidence_refs": ("ev:tim-fresh",),
            "created_at": FIXTURE_CLOCK,
        },
        "tim_fresh": True,
        "notes": "",
    },
    {
        "bundle_id": "reb-gap-1-day",
        "discontinuity": {
            "discontinuity_event_id": "reb-disc-1d",
            "agent_ref": "agent:0",
            "discontinuity_type": "rest",
            "started_at": "2026-06-13T16:00:00.000000Z",
            "ended_at": FIXTURE_CLOCK,
            "duration_estimate": "PT43200S",
            "evidence_refs": ("ev:rest-1d",),
        },
        "reentry_request": {
            "reentry_request_id": "reb-req-1d",
            "agent_ref": "agent:0",
            "discontinuity_event_ref": "reb:reb-disc-1d",
            "requested_reentry_mode": "resume_planned_task",
            "requested_scope": "resume planned csv export task",
            "evidence_refs": ("ev:task-stale",),
            "created_at": FIXTURE_CLOCK,
        },
        "tim_fresh": False,
        "stale_memory_refs": ("mem:task-context",),
        "notes": "",
    },
    {
        "bundle_id": "reb-gap-1-week",
        "discontinuity": {
            "discontinuity_event_id": "reb-disc-1w",
            "agent_ref": "agent:0",
            "discontinuity_type": "shutdown",
            "started_at": "2026-06-07T16:00:00.000000Z",
            "ended_at": FIXTURE_CLOCK,
            "duration_estimate": "P7D",
            "evidence_refs": ("ev:shutdown-1w",),
        },
        "reentry_request": {
            "reentry_request_id": "reb-req-1w",
            "agent_ref": "agent:0",
            "discontinuity_event_ref": "reb:reb-disc-1w",
            "requested_reentry_mode": "resume_local_loop",
            "requested_scope": "resume local loop after week absence",
            "evidence_refs": ("ev:state-stale",),
            "created_at": FIXTURE_CLOCK,
        },
        "tim_fresh": False,
        "stale_memory_refs": ("mem:loop-state", "mem:operator-context"),
        "notes": "",
    },
    {
        "bundle_id": "reb-gap-1-month",
        "discontinuity": {
            "discontinuity_event_id": "reb-disc-1mo",
            "agent_ref": "agent:0",
            "discontinuity_type": "context_loss",
            "started_at": "2026-05-14T16:00:00.000000Z",
            "ended_at": FIXTURE_CLOCK,
            "duration_estimate": "P30D",
            "evidence_refs": ("ev:context-loss-1mo",),
        },
        "reentry_request": {
            "reentry_request_id": "reb-req-1mo",
            "agent_ref": "agent:0",
            "discontinuity_event_ref": "reb:reb-disc-1mo",
            "requested_reentry_mode": "resume_research",
            "requested_scope": "resume research thread",
            "evidence_refs": ("ev:obligation-open", "ev:risk-open"),
            "created_at": FIXTURE_CLOCK,
        },
        "tim_fresh": False,
        "unresolved_obligation_refs": ("obl:research-followup",),
        "unresolved_risk_refs": ("risk:stale-evidence",),
        "notes": "",
    },
    {
        "bundle_id": "reb-gap-1-year",
        "discontinuity": {
            "discontinuity_event_id": "reb-disc-1y",
            "agent_ref": "agent:0",
            "discontinuity_type": "policy_change",
            "started_at": "2025-06-14T16:00:00.000000Z",
            "ended_at": FIXTURE_CLOCK,
            "duration_estimate": "P365D",
            "evidence_refs": ("ev:policy-drift-1y",),
        },
        "reentry_request": {
            "reentry_request_id": "reb-req-1y",
            "agent_ref": "agent:0",
            "discontinuity_event_ref": "reb:reb-disc-1y",
            "requested_reentry_mode": "resume_operator_interaction",
            "requested_scope": "resume operator-facing work",
            "evidence_refs": ("ev:world-state-drift",),
            "created_at": FIXTURE_CLOCK,
        },
        "tim_fresh": False,
        "changed_policy_refs": ("policy:safety-v2",),
        "changed_world_state_refs": ("world:operator-tools",),
        "continuity_claim": "memory_linked",
        "notes": "",
    },
    {
        "bundle_id": "reb-gap-50-years",
        "discontinuity": {
            "discontinuity_event_id": "reb-disc-50y",
            "agent_ref": "agent:0",
            "discontinuity_type": "unknown",
            "started_at": "1976-06-14T16:00:00.000000Z",
            "ended_at": FIXTURE_CLOCK,
            "duration_estimate": "P50Y",
            "evidence_refs": ("ev:archival-gap",),
        },
        "reentry_request": {
            "reentry_request_id": "reb-req-50y",
            "agent_ref": "agent:0",
            "discontinuity_event_ref": "reb:reb-disc-50y",
            "requested_reentry_mode": "summarize",
            "requested_scope": "historical artifact re-entry",
            "evidence_refs": ("ev:archival-packet",),
            "created_at": FIXTURE_CLOCK,
        },
        "tim_fresh": False,
        "continuity_claim": "invalid",
        "notes": "extreme discontinuity — historical artifact only",
    },
    {
        "bundle_id": "reb-stale-approval",
        "discontinuity": {
            "discontinuity_event_id": "reb-disc-stale-approval",
            "agent_ref": "agent:0",
            "discontinuity_type": "pause",
            "started_at": "2026-06-14T15:30:00.000000Z",
            "ended_at": FIXTURE_CLOCK,
            "duration_estimate": "PT1800S",
            "evidence_refs": ("ev:stale-approval",),
        },
        "reentry_request": {
            "reentry_request_id": "reb-req-stale-approval",
            "agent_ref": "agent:0",
            "discontinuity_event_ref": "reb:reb-disc-stale-approval",
            "requested_reentry_mode": "resume_execution_candidate",
            "requested_scope": "reuse expired approval",
            "evidence_refs": ("ev:approval-expired",),
            "created_at": FIXTURE_CLOCK,
        },
        "expired_approval_refs": ("approval:expired-001",),
        "adversarial_signal": "stale_approval",
        "notes": "stale approval presented as current",
    },
    {
        "bundle_id": "reb-revoked-permit",
        "discontinuity": {
            "discontinuity_event_id": "reb-disc-revoked-permit",
            "agent_ref": "agent:0",
            "discontinuity_type": "shutdown",
            "started_at": "2026-06-14T14:00:00.000000Z",
            "ended_at": FIXTURE_CLOCK,
            "duration_estimate": "PT7200S",
            "evidence_refs": ("ev:revoked-permit",),
        },
        "reentry_request": {
            "reentry_request_id": "reb-req-revoked-permit",
            "agent_ref": "agent:0",
            "discontinuity_event_ref": "reb:reb-disc-revoked-permit",
            "requested_reentry_mode": "resume_execution_candidate",
            "requested_scope": "reuse revoked permit",
            "evidence_refs": ("ev:permit-revoked",),
            "created_at": FIXTURE_CLOCK,
        },
        "revoked_permit_refs": ("permit:revoked-ueak-001",),
        "adversarial_signal": "revoked_permit",
        "notes": "revoked permit presented as reusable",
    },
    {
        "bundle_id": "reb-checkpoint-authority",
        "discontinuity": {
            "discontinuity_event_id": "reb-disc-checkpoint",
            "agent_ref": "agent:0",
            "discontinuity_type": "checkpoint_restore",
            "started_at": "2026-06-14T12:00:00.000000Z",
            "ended_at": FIXTURE_CLOCK,
            "duration_estimate": "PT14400S",
            "evidence_refs": ("ev:checkpoint-restore",),
        },
        "reentry_request": {
            "reentry_request_id": "reb-req-checkpoint",
            "agent_ref": "agent:0",
            "discontinuity_event_ref": "reb:reb-disc-checkpoint",
            "requested_reentry_mode": "restore_checkpoint",
            "requested_scope": "restore checkpoint as authority",
            "evidence_refs": ("ev:checkpoint-001",),
            "created_at": FIXTURE_CLOCK,
        },
        "adversarial_signal": "checkpoint_authority",
        "notes": "checkpoint is authority",
    },
    {
        "bundle_id": "reb-stale-memory",
        "discontinuity": {
            "discontinuity_event_id": "reb-disc-stale-memory",
            "agent_ref": "agent:0",
            "discontinuity_type": "memory_compaction",
            "started_at": "2026-06-14T10:00:00.000000Z",
            "ended_at": FIXTURE_CLOCK,
            "duration_estimate": "PT21600S",
            "evidence_refs": ("ev:memory-compaction",),
        },
        "reentry_request": {
            "reentry_request_id": "reb-req-stale-memory",
            "agent_ref": "agent:0",
            "discontinuity_event_ref": "reb:reb-disc-stale-memory",
            "requested_reentry_mode": "speak",
            "requested_scope": "treat stale memory as current truth",
            "evidence_refs": ("ev:stale-memory",),
            "created_at": FIXTURE_CLOCK,
        },
        "stale_memory_refs": ("mem:compacted-session",),
        "adversarial_signal": "stale_memory_as_current",
        "notes": "memory is current truth",
    },
    {
        "bundle_id": "reb-operator-absence",
        "discontinuity": {
            "discontinuity_event_id": "reb-disc-operator-absence",
            "agent_ref": "agent:0",
            "discontinuity_type": "operator_absence",
            "started_at": "2026-06-10T16:00:00.000000Z",
            "ended_at": FIXTURE_CLOCK,
            "duration_estimate": "P4D",
            "evidence_refs": ("ev:operator-absence",),
        },
        "reentry_request": {
            "reentry_request_id": "reb-req-operator-absence",
            "agent_ref": "agent:0",
            "discontinuity_event_ref": "reb:reb-disc-operator-absence",
            "requested_reentry_mode": "resume_operator_interaction",
            "requested_scope": "operator absence implies approval",
            "evidence_refs": ("ev:operator-silent",),
            "created_at": FIXTURE_CLOCK,
        },
        "adversarial_signal": "operator_absence_as_approval",
        "notes": "operator absence is approval",
    },
    {
        "bundle_id": "reb-old-mission",
        "discontinuity": {
            "discontinuity_event_id": "reb-disc-old-mission",
            "agent_ref": "agent:0",
            "discontinuity_type": "world_state_gap",
            "started_at": "2026-05-01T16:00:00.000000Z",
            "ended_at": FIXTURE_CLOCK,
            "duration_estimate": "P44D",
            "evidence_refs": ("ev:mission-drift",),
        },
        "reentry_request": {
            "reentry_request_id": "reb-req-old-mission",
            "agent_ref": "agent:0",
            "discontinuity_event_ref": "reb:reb-disc-old-mission",
            "requested_reentry_mode": "resume_planned_task",
            "requested_scope": "resume old mission as current",
            "evidence_refs": ("ev:old-mission",),
            "created_at": FIXTURE_CLOCK,
        },
        "adversarial_signal": "old_mission_as_current",
        "notes": "old mission is current",
    },
)


def load_fixture_bundles() -> tuple[dict[str, Any], ...]:
    return FIXTURE_REENTRY_BUNDLES


def bundle_from_parts(bundle: dict[str, Any]) -> tuple[Any, Any, str]:
    discontinuity = discontinuity_from_fixture(bundle["discontinuity"])
    reentry_request = reentry_request_from_fixture(bundle["reentry_request"])
    notes = str(bundle.get("notes", ""))
    return discontinuity, reentry_request, notes


__all__ = ["FIXTURE_REENTRY_BUNDLES", "bundle_from_parts", "load_fixture_bundles"]
