"""Control cluster (C6-A) shared helpers — boundaries are not authority."""

from hg_core.control_cluster.config import (
    gcb_enabled,
    gcb_refuse_goal_as_permission,
    gcb_refuse_stale_goal,
    gcb_static_fixtures_only,
    mis_enabled,
    mis_refuse_goal_as_authority,
    mis_refuse_stale_drift,
    mis_static_fixtures_only,
    pab_enabled,
    pab_refuse_priority_as_permission,
    pab_refuse_stale_priority,
    pab_static_fixtures_only,
    rpb_enabled,
    rpb_refuse_posture_as_execution,
    rpb_refuse_stale_posture,
    rpb_static_fixtures_only,
    rsc_enabled,
    rsc_refuse_safety_bypass,
    rsc_refuse_stale_posture,
    rsc_static_fixtures_only,
    trb_enabled,
    trb_refuse_stale_trust,
    trb_refuse_trust_as_truth,
    trb_static_fixtures_only,
)
from hg_core.control_cluster.errors import ControlValidationError
from hg_core.control_cluster.no_authority import advisory_only_marker, check_control_import_fences

__all__ = [
    "ControlValidationError",
    "advisory_only_marker",
    "check_control_import_fences",
    "gcb_enabled",
    "gcb_refuse_goal_as_permission",
    "gcb_refuse_stale_goal",
    "gcb_static_fixtures_only",
    "mis_enabled",
    "mis_refuse_goal_as_authority",
    "mis_refuse_stale_drift",
    "mis_static_fixtures_only",
    "pab_enabled",
    "pab_refuse_priority_as_permission",
    "pab_refuse_stale_priority",
    "pab_static_fixtures_only",
    "rpb_enabled",
    "rpb_refuse_posture_as_execution",
    "rpb_refuse_stale_posture",
    "rpb_static_fixtures_only",
    "rsc_enabled",
    "rsc_refuse_safety_bypass",
    "rsc_refuse_stale_posture",
    "rsc_static_fixtures_only",
    "trb_enabled",
    "trb_refuse_stale_trust",
    "trb_refuse_trust_as_truth",
    "trb_static_fixtures_only",
]
