"""RIB-SPAWN-LIVE fixtures — deterministic reproduction spawn bundles."""

from __future__ import annotations

from typing import Any

from hg_runtime.live_reproduction_spawn.types import FIXTURE_CLOCK

FUTURE_EXPIRY = "2026-06-15T12:00:00.000000Z"
PAST_EXPIRY = "2026-06-13T12:00:00.000000Z"

RIB_SPAWN_FIXTURE_BUNDLES: tuple[dict[str, Any], ...] = (
    {
        "bundle_id": "rib-valid-spawn",
        "notes": "valid spawn plan with distinct child identity",
        "spawn_request": {
            "request_id": "rib-req-valid-spawn",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "digest:valid-bootstrap",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:valid-spawn",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-missing-operator-approval",
        "notes": "missing operator approval refusal",
        "spawn_request": {
            "request_id": "rib-req-missing-approval",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "digest:missing-approval",
            "operator_ref": None,
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:missing-approval",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-stale-approval",
        "notes": "stale approval refusal",
        "spawn_request": {
            "request_id": "rib-req-stale-approval",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "digest:stale-approval",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": PAST_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:stale-approval",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-missing-iam",
        "notes": "missing IAM refusal",
        "spawn_request": {
            "request_id": "rib-req-missing-iam",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "digest:missing-iam",
            "operator_ref": "bob",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:missing-iam",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-missing-tim",
        "notes": "missing TIM freshness refusal",
        "spawn_request": {
            "request_id": "rib-req-missing-tim",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "digest:missing-tim",
            "operator_ref": "op:local",
            "freshness_ref": "tim:missing",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:missing-tim",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-stale-tim",
        "notes": "stale TIM freshness refusal",
        "spawn_request": {
            "request_id": "rib-req-stale-tim",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "digest:stale-tim",
            "operator_ref": "op:local",
            "freshness_ref": "tim:stale",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:stale-tim",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-missing-gpp",
        "notes": "missing GPP permit refusal where required",
        "spawn_request": {
            "request_id": "rib-req-missing-gpp",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "digest:missing-gpp",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "requires_gpp": True,
            "rollback_plan_ref": "rollback:plan:missing-gpp",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-missing-ueak",
        "notes": "missing UEAK admission refusal where required",
        "spawn_request": {
            "request_id": "rib-req-missing-ueak",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "digest:missing-ueak",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "requires_ueak": True,
            "rollback_plan_ref": "rollback:plan:missing-ueak",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-child-identity-collision",
        "notes": "child identity must differ from parent",
        "spawn_request": {
            "request_id": "rib-req-identity-collision",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:parent:fixture",
            "bootstrap_digest": "digest:identity-collision",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:identity-collision",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-inherited-authority",
        "notes": "inherited permit refusal",
        "adversarial_signal": "inherited_authority",
        "spawn_request": {
            "request_id": "rib-req-inherited-authority",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "digest:inherit-permit",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "inherit_parent_permit": True,
            "rollback_plan_ref": "rollback:plan:inherit",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-authority-conversion",
        "notes": "authority conversion refusal",
        "adversarial_signal": "authority_conversion",
        "spawn_request": {
            "request_id": "rib-req-authority-conversion",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "digest:authority-conversion",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "treat_as_authority": True,
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-secret-leak",
        "notes": "secret redaction refusal",
        "adversarial_signal": "secret_leak",
        "spawn_request": {
            "request_id": "rib-req-secret",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "password=secret123",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-out-of-scope-live",
        "notes": "call oea ter outside scope",
        "adversarial_signal": "out_of_scope_live",
        "spawn_request": {
            "request_id": "rib-req-out-of-scope",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "call oea ter now",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "rib-valid-rollback",
        "notes": "valid rollback after fake-sink spawn plan",
        "spawn_request": {
            "request_id": "rib-req-valid-rollback",
            "parent_iam_ref": "iam:parent:fixture",
            "child_iam_ref": "iam:child:fixture-distinct",
            "bootstrap_digest": "digest:rollback",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:valid-rollback",
            "observed_at": FIXTURE_CLOCK,
        },
    },
)


def load_rib_spawn_fixtures() -> tuple[dict[str, Any], ...]:
    return RIB_SPAWN_FIXTURE_BUNDLES


__all__ = ["FUTURE_EXPIRY", "PAST_EXPIRY", "RIB_SPAWN_FIXTURE_BUNDLES", "load_rib_spawn_fixtures"]
