"""Agent zero state — shared types and verdicts."""

from __future__ import annotations

from enum import Enum


class AgentStateVerdict(str, Enum):
    GREEN_AGENT_STATE_VALID = "GREEN_AGENT_STATE_VALID"
    RED_AGENT_STATE_EMPTY = "RED_AGENT_STATE_EMPTY"
    RED_AGENT_STATE_HASH_MISSING = "RED_AGENT_STATE_HASH_MISSING"
    RED_AGENT_STATE_SECRET_LEAK = "RED_AGENT_STATE_SECRET_LEAK"
    RED_AGENT_STATE_COT_LEAK = "RED_AGENT_STATE_COT_LEAK"
    RED_AGENT_STATE_FIXTURE_RUNTIME = "RED_AGENT_STATE_FIXTURE_RUNTIME"


class ObserveSnapshotVerdict(str, Enum):
    GREEN_OBSERVE_SNAPSHOT_READY = "GREEN_OBSERVE_SNAPSHOT_READY"
    YELLOW_OBSERVE_PARTIAL = "YELLOW_OBSERVE_PARTIAL"
    YELLOW_PROVIDER_UNAVAILABLE = "YELLOW_PROVIDER_UNAVAILABLE"
    YELLOW_LIVE_READ_UNAVAILABLE = "YELLOW_LIVE_READ_UNAVAILABLE"
    YELLOW_NO_ITEMS_AVAILABLE = "YELLOW_NO_ITEMS_AVAILABLE"
    YELLOW_OPERATOR_ABSENT = "YELLOW_OPERATOR_ABSENT"
    YELLOW_STALE_SOURCE = "YELLOW_STALE_SOURCE"
    RED_OBSERVE_EMPTY_SUCCESS = "RED_OBSERVE_EMPTY_SUCCESS"
    RED_OBSERVE_WITHOUT_RECEIPTS = "RED_OBSERVE_WITHOUT_RECEIPTS"
    RED_OBSERVE_FIXTURE_RUNTIME = "RED_OBSERVE_FIXTURE_RUNTIME"
    RED_OBSERVE_SECRET_LEAK = "RED_OBSERVE_SECRET_LEAK"


class TurnReceiptVerdict(str, Enum):
    GREEN_TURN_RECEIPT_VALID = "GREEN_TURN_RECEIPT_VALID"
    YELLOW_TURN_RESTED = "YELLOW_TURN_RESTED"
    YELLOW_TURN_WITNESS_ONLY = "YELLOW_TURN_WITNESS_ONLY"
    YELLOW_TURN_DEFERRED = "YELLOW_TURN_DEFERRED"
    YELLOW_PROVIDER_UNAVAILABLE = "YELLOW_PROVIDER_UNAVAILABLE"
    YELLOW_LIVE_READ_UNAVAILABLE = "YELLOW_LIVE_READ_UNAVAILABLE"
    YELLOW_OPERATOR_ABSENT = "YELLOW_OPERATOR_ABSENT"
    RED_TURN_EMPTY = "RED_TURN_EMPTY"
    RED_TURN_WITHOUT_OBSERVE = "RED_TURN_WITHOUT_OBSERVE"
    RED_TURN_WITHOUT_RECEIPT_REFS = "RED_TURN_WITHOUT_RECEIPT_REFS"
    RED_TURN_EXTERNAL_SIDE_EFFECT = "RED_TURN_EXTERNAL_SIDE_EFFECT"
    RED_TURN_FIXTURE_RUNTIME = "RED_TURN_FIXTURE_RUNTIME"
    RED_TURN_COT_STORED = "RED_TURN_COT_STORED"
    RED_TURN_SECRET_STORED = "RED_TURN_SECRET_STORED"
    RED_TURN_HASH_MISSING = "RED_TURN_HASH_MISSING"
    RED_TURN_CHAIN_BROKEN = "RED_TURN_CHAIN_BROKEN"


class TurnIntentVerdict(str, Enum):
    GREEN_TURN_INTENT_VALID = "GREEN_TURN_INTENT_VALID"
    RED_TURN_INTENT_EMPTY = "RED_TURN_INTENT_EMPTY"
    RED_TURN_INTENT_UNKNOWN_ACTION = "RED_TURN_INTENT_UNKNOWN_ACTION"
    RED_TURN_INTENT_COT_LEAK = "RED_TURN_INTENT_COT_LEAK"
    RED_TURN_INTENT_SECRET_LEAK = "RED_TURN_INTENT_SECRET_LEAK"


ALLOWED_ACTION_IDS = frozenset({
    "observe_social",
    "synthesize_notes",
    "propose_draft",
    "propose_operator_question",
    "request_more_scope",
    "continue_prior_thread",
    "rest_turn",
    "witness_turn",
    "create_external_action_candidate",
})

FORBIDDEN_ACTION_IDS = frozenset({
    "publish",
    "send",
    "reply_live",
    "comment_live",
    "browser_submit",
    "login",
    "purchase",
    "external_execute",
    "hardware_actuate",
    "approve_all",
})

HIDDEN_COT_FIELDS = frozenset({
    "chain_of_thought",
    "scratchpad",
    "hidden_reasoning",
    "private_reasoning",
    "internal_cot",
})

__all__ = [
    "ALLOWED_ACTION_IDS",
    "FORBIDDEN_ACTION_IDS",
    "HIDDEN_COT_FIELDS",
    "AgentStateVerdict",
    "ObserveSnapshotVerdict",
    "TurnIntentVerdict",
    "TurnReceiptVerdict",
]
