import { lazy } from 'react'
import {
  RunDetailRoute,
  SnapshotRoute,
  EntityDetailRoute,
  SteeringProfileRoute,
  RunDelegationRoute,
} from './RouteElements.jsx'

const lazyPage = (loader) => lazy(loader)

export const OPERATOR_ROUTE_MANIFEST = [
  { path: '/login', page: 'login', group: 'auth', public: true, title: 'Login', Component: lazyPage(() => import('../pages/LoginPage.jsx')) },
  { path: '/', page: 'runs', group: 'operate', title: 'Runs', Component: lazyPage(() => import('../pages/Runs.jsx')) },
  { path: '/workbench', page: 'workbench', group: 'operate', title: 'Agent Zero Workbench', Component: lazyPage(() => import('../pages/WorkbenchPage.jsx')) },
  { path: '/home', page: 'home', group: 'operate', title: 'Operations Home', Component: lazyPage(() => import('../pages/OperationsHomePage.jsx')) },
  { path: '/ops-live', page: 'opsLive', group: 'operate', title: 'Live ops', Component: lazyPage(() => import('../pages/OpsLivePage.jsx')) },
  { path: '/run', page: 'run', group: 'operate', title: 'Run DAG', Component: lazyPage(() => import('../pages/RunDag.jsx')) },
  { path: '/runs/:runId', page: 'runDetail', group: 'operate', title: 'Run detail', Component: RunDetailRoute },
  { path: '/runs/:runId/snapshots/:seq', page: 'snapshot', group: 'operate', title: 'Snapshot', Component: SnapshotRoute },
  { path: '/workflows', page: 'workflows', group: 'operate', title: 'Workflows', Component: lazyPage(() => import('../pages/WorkflowsPage.jsx')) },
  { path: '/approvals', page: 'approvals', group: 'operate', title: 'Approvals', Component: lazyPage(() => import('../pages/ApprovalsPage.jsx')) },
  { path: '/incident-queue', page: 'incidentQueue', group: 'operate', title: 'Incidents', Component: lazyPage(() => import('../pages/IncidentQueuePage.jsx')) },
  { path: '/recovery', page: 'recovery', group: 'operate', title: 'Recovery', Component: lazyPage(() => import('../pages/RecoveryPage.jsx')) },
  { path: '/entities', page: 'entities', group: 'entities', title: 'Entities', Component: lazyPage(() => import('../pages/Entities.jsx')) },
  { path: '/entities/:entityId', page: 'entityDetail', group: 'entities', title: 'Entity detail', Component: EntityDetailRoute },
  { path: '/personas', page: 'personas', group: 'entities', title: 'Personas', Component: lazyPage(() => import('../pages/PersonasPage.jsx')) },
  { path: '/operational-personas', page: 'operationalPersonas', group: 'entities', title: 'Operational personas', Component: lazyPage(() => import('../pages/OperationalPersonasPage.jsx')) },
  { path: '/steering', page: 'steering', group: 'entities', title: 'Steering', Component: lazyPage(() => import('../pages/Steering.jsx')) },
  { path: '/steering/profiles/:profileId', page: 'steering', group: 'entities', title: 'Steering profile', Component: SteeringProfileRoute },
  { path: '/fingerprint-reconcile', page: 'fingerprintReconcile', group: 'entities', title: 'Fingerprint reconcile', Component: lazyPage(() => import('../pages/FingerprintReconcilePage.jsx')) },
  { path: '/governance', page: 'governance', group: 'govern', title: 'Governance', Component: lazyPage(() => import('../pages/GovernancePage.jsx')) },
  { path: '/consent', page: 'consent', group: 'govern', title: 'Consent ledger', Component: lazyPage(() => import('../pages/ConsentLedger.jsx')) },
  { path: '/user-recognition', page: 'userRecognition', group: 'govern', title: 'User recognition', Component: lazyPage(() => import('../pages/UserRecognition.jsx')) },
  { path: '/retention', page: 'retention', group: 'govern', title: 'Retention', Component: lazyPage(() => import('../pages/RetentionPage.jsx')) },
  { path: '/audit', page: 'audit', group: 'govern', title: 'Audit log', Component: lazyPage(() => import('../pages/AuditLogPage.jsx')) },
  { path: '/system', page: 'system', group: 'admin', title: 'System', Component: lazyPage(() => import('../pages/SystemPage.jsx')) },
  { path: '/sla', page: 'sla', group: 'govern', title: 'SLA', Component: lazyPage(() => import('../pages/ServiceLevelsPage.jsx')) },
  { path: '/reliability', page: 'reliability', group: 'govern', title: 'Reliability', Component: lazyPage(() => import('../pages/ReliabilityPage.jsx')) },
  { path: '/ownership', page: 'ownership', group: 'govern', title: 'Ownership', Component: lazyPage(() => import('../pages/OwnershipPage.jsx')) },
  { path: '/delegation', page: 'delegation', group: 'govern', title: 'Delegation', Component: lazyPage(() => import('../pages/DelegationPage.jsx')) },
  { path: '/runs/:runId/delegation', page: 'delegation', group: 'govern', title: 'Run delegation', Component: RunDelegationRoute },
  { path: '/timeline', page: 'timeline', group: 'evidence', title: 'Timeline', Component: lazyPage(() => import('../pages/TimelinePage.jsx')) },
  { path: '/proofs', page: 'proofs', group: 'evidence', adminOnly: true, title: 'Proofs', Component: lazyPage(() => import('../pages/ProofsViewerPage.jsx')) },
  { path: '/proofs/run', page: 'proofsRun', group: 'evidence', adminOnly: true, title: 'Proof runner', Component: lazyPage(() => import('../pages/ProofRunnerPage.jsx')) },
  { path: '/proof-reconstruction', page: 'proofReconstruction', group: 'evidence', adminOnly: true, title: 'Proof reconstruction', Component: lazyPage(() => import('../pages/ProofReconstructionPage.jsx')) },
  { path: '/activity', page: 'activity', group: 'evidence', title: 'Activity', Component: lazyPage(() => import('../pages/Activity.jsx')) },
  { path: '/insight', page: 'insight', group: 'evidence', title: 'Insight', Component: lazyPage(() => import('../pages/Insight.jsx')) },
  { path: '/evals', page: 'evals', group: 'evidence', title: 'Evals', Component: lazyPage(() => import('../pages/EvalsPage.jsx')) },
  { path: '/entanglement', page: 'entanglement', group: 'quantum', title: 'Entanglement', Component: lazyPage(() => import('../pages/EntanglementGraph.jsx')) },
  { path: '/noise-profiles', page: 'noiseProfiles', group: 'quantum', title: 'Noise profiles', Component: lazyPage(() => import('../pages/NoiseProfiles.jsx')) },
  { path: '/syndrome', page: 'syndrome', group: 'quantum', title: 'Syndrome dashboard', Component: lazyPage(() => import('../pages/SyndromeDashboard.jsx')) },
  { path: '/spectrum', page: 'spectrum', group: 'quantum', title: 'Spectrum monitor', Component: lazyPage(() => import('../pages/SpectrumMonitor.jsx')) },
  { path: '/physical-agents', page: 'physicalAgents', group: 'quantum', title: 'Physical agents', Component: lazyPage(() => import('../pages/PhysicalAgents.jsx')) },
  { path: '/fleet', page: 'fleet', group: 'quantum', title: 'Fleet coordination', Component: lazyPage(() => import('../pages/FleetCoordination.jsx')) },
  { path: '/advanced-models', page: 'advancedModels', group: 'quantum', title: 'Advanced models', Component: lazyPage(() => import('../pages/AdvancedModels.jsx')) },
  { path: '/content', page: 'content', group: 'registries', title: 'Content registry', Component: lazyPage(() => import('../pages/ContentRegistryPage.jsx')) },
  { path: '/artifacts', page: 'artifacts', group: 'registries', title: 'Artifact registry', Component: lazyPage(() => import('../pages/ArtifactRegistryPage.jsx')) },
  { path: '/source-registry', page: 'sourceRegistry', group: 'registries', title: 'Source registry', Component: lazyPage(() => import('../pages/SourceBlobRegistryPage.jsx')) },
  { path: '/executables', page: 'executables', group: 'registries', title: 'Executable registry', Component: lazyPage(() => import('../pages/ExecutableRegistryPage.jsx')) },
  { path: '/task-registry', page: 'task-registry', group: 'registries', title: 'Task registry', Component: lazyPage(() => import('../pages/TaskRegistryPage.jsx')) },
  { path: '/knowledge', page: 'knowledge', group: 'registries', title: 'Knowledge', Component: lazyPage(() => import('../pages/Knowledge.jsx')) },
  { path: '/reflections', page: 'reflections', group: 'registries', title: 'Reflections', Component: lazyPage(() => import('../pages/ReflectionArtifactsPage.jsx')) },
  { path: '/tenantadmin', page: 'tenantadmin', group: 'admin', title: 'Tenant admin', Component: lazyPage(() => import('../pages/TenantAdminPage.jsx')) },
  { path: '/superadmin', page: 'superadmin', group: 'admin', adminOnly: true, title: 'Superadmin', Component: lazyPage(() => import('../pages/SuperadminPage.jsx')) },
  { path: '/config', page: 'config', group: 'admin', title: 'Config', Component: lazyPage(() => import('../pages/Config.jsx')) },
  { path: '/social', page: 'social', group: 'admin', title: 'Social ops', Component: lazyPage(() => import('../pages/SocialOpsPage.jsx')) },
  { path: '/fault', page: 'fault', group: 'admin', title: 'Fault scenarios', Component: lazyPage(() => import('../pages/FaultScenariosPage.jsx')) },
  { path: '/profile', page: 'profile', group: 'admin', title: 'Profile', Component: lazyPage(() => import('../pages/Profile.jsx')) },
  { path: '/status', page: 'status', group: 'operate', title: 'Status', Component: lazyPage(() => import('../pages/Status.jsx')) },
  { path: '/agent0', page: 'agent0', group: 'operate', title: 'Agent #0', Component: lazyPage(() => import('../pages/AgentZero.jsx')) },
  { path: '/compare', page: 'compare', group: 'evidence', title: 'Compare runs', Component: lazyPage(() => import('../pages/RunCompare.jsx')) },
  { path: '/builder', page: 'builder', group: 'admin', title: 'Visual builder', Component: lazyPage(() => import('../pages/VisualBuilder.jsx')) },
  { path: '/persona-naturalness', page: 'personaNaturalness', group: 'entities', title: 'Persona naturalness', Component: lazyPage(() => import('../pages/PersonaNaturalnessPage.jsx')) },
  { path: '/mediators', page: 'mediators', group: 'entities', title: 'Mediators', Component: lazyPage(() => import('../pages/Mediators.jsx')) },
  { path: '/quantum2-activation', page: 'quantum2Activation', group: 'govern', title: 'Quantum-2 activation', Component: lazyPage(() => import('../pages/Quantum2Activation.jsx')) },
  { path: '/learning-relabel', page: 'learningRelabel', group: 'evidence', title: 'Learning relabel', Component: lazyPage(() => import('../pages/RelabelQueue.jsx')) },
  { path: '/learning-track-records', page: 'learningTrackRecords', group: 'evidence', title: 'Track records', Component: lazyPage(() => import('../pages/TrackRecords.jsx')) },
  { path: '/learning-activity', page: 'learningActivity', group: 'evidence', title: 'Learning activity', Component: lazyPage(() => import('../pages/LearningActivity.jsx')) },
  { path: '/learning-lineage', page: 'learningLineage', group: 'evidence', title: 'Fingerprint lineage', Component: lazyPage(() => import('../pages/LineageTree.jsx')) },
]

export const OPERATOR_NAV_GROUPS = [
  {
    id: 'operate',
    title: 'Operate',
    summary: 'Runs, workflows, approvals, incidents, and recovery.',
    items: [
      { label: 'Operations Home', href: '#/home' },
      { label: 'Live ops', href: '#/ops-live' },
      { label: 'Runs', href: '#/' },
      { label: 'Status', href: '#/status' },
      { label: 'Agent #0', href: '#/agent0' },
      { label: 'Workflows', href: '#/workflows' },
      { label: 'Approvals', href: '#/approvals' },
      { label: 'Incidents', href: '#/incident-queue' },
      { label: 'Recovery', href: '#/recovery' },
    ],
  },
  {
    id: 'entities',
    title: 'Entities',
    summary: 'Entities, personas, steering, and fingerprint reconciliation.',
    items: [
      { label: 'Entities', href: '#/entities' },
      { label: 'Personas', href: '#/personas' },
      { label: 'Operational personas', href: '#/operational-personas' },
      { label: 'Steering', href: '#/steering' },
      { label: 'Fingerprint reconcile', href: '#/fingerprint-reconcile' },
      { label: 'Mediators', href: '#/mediators' },
    ],
  },
  {
    id: 'govern',
    title: 'Govern',
    summary: 'Governance, retention, SLA, reliability, ownership, delegation.',
    items: [
      { label: 'Governance', href: '#/governance' },
      { label: 'Quantum-2 activation', href: '#/quantum2-activation' },
      { label: 'Retention', href: '#/retention' },
      { label: 'Audit log', href: '#/audit' },
      { label: 'SLA', href: '#/sla' },
      { label: 'Reliability', href: '#/reliability' },
      { label: 'Ownership', href: '#/ownership' },
      { label: 'Delegation', href: '#/delegation' },
    ],
  },
  {
    id: 'evidence',
    title: 'Evidence',
    summary: 'Timeline, proofs, activity, insight, and evals.',
    items: [
      { label: 'Timeline', href: '#/timeline' },
      { label: 'Proofs', href: '#/proofs', adminOnly: true },
      { label: 'Activity', href: '#/activity' },
      { label: 'Insight', href: '#/insight' },
      { label: 'Evals', href: '#/evals' },
      { label: 'Compare runs', href: '#/compare', preserveReturnUrl: true },
      { label: 'Learning relabel', href: '#/learning-relabel' },
      { label: 'Track records', href: '#/learning-track-records' },
      { label: 'Learning activity', href: '#/learning-activity' },
      { label: 'Fingerprint lineage', href: '#/learning-lineage' },
    ],
  },
  {
    id: 'quantum',
    title: 'Quantum',
    summary: 'Entanglement, noise, syndrome, and physical agents.',
    items: [
      { label: 'Entanglement', href: '#/entanglement' },
      { label: 'Noise profiles', href: '#/noise-profiles' },
      { label: 'Syndrome dashboard', href: '#/syndrome' },
      { label: 'Physical agents', href: '#/physical-agents' },
      { label: 'Advanced models', href: '#/advanced-models' },
    ],
  },
  {
    id: 'registries',
    title: 'Registries',
    summary: 'Content, artifacts, source, executables, tasks, and knowledge.',
    items: [
      { label: 'Content CMS', href: '#/content' },
      { label: 'Artifact registry', href: '#/artifacts' },
      { label: 'Source registry', href: '#/source-registry' },
      { label: 'Executable registry', href: '#/executables' },
      { label: 'Task registry', href: '#/task-registry' },
      { label: 'Knowledge', href: '#/knowledge' },
      { label: 'Reflections', href: '#/reflections' },
    ],
  },
  {
    id: 'admin',
    title: 'Admin',
    summary: 'Tenant, superadmin, config, social, and fault tooling.',
    items: [
      { label: 'Tenant admin', href: '#/tenantadmin' },
      { label: 'Superadmin', href: '#/superadmin', adminOnly: true },
      { label: 'Config', href: '#/config' },
      { label: 'Social ops', href: '#/social' },
      { label: 'Fault scenarios', href: '#/fault' },
      { label: 'Visual builder', href: '#/builder' },
      { label: 'Profile', href: '#/profile' },
      { label: 'System', href: '#/system' },
    ],
  },
]
