"""Real soak launch schemas and enums."""

from __future__ import annotations

import json
import uuid
from enum import Enum
from pathlib import Path
from typing import Any

WORKSPACE = Path(__file__).resolve().parents[2]
POLICY_PATH = WORKSPACE / "configs/agent_zero/real_soak_launch_policy.json"
STORE_ROOT = WORKSPACE / ".hg-local/agent_zero/real_soak"


class RealSoakLaunchVerdict(str, Enum):
    GREEN_LAUNCH_READY = "GREEN_AUTONOMOUS_AGENT_ZERO_PHASE_24_5_REAL_SOAK_LAUNCH_READY"
    YELLOW_PHASE18 = "YELLOW_PHASE18_LIVE_SMOKE_NOT_RUN_ACCEPTED_FOR_LAUNCH_READINESS"
    YELLOW_PHASE19 = "YELLOW_PHASE19_NO_LIVE_PROOF_ACCEPTED_FOR_LAUNCH_READINESS"
    YELLOW_CREDENTIALS = "YELLOW_MOLTBOOK_CREDENTIALS_MISSING"
    YELLOW_ENVELOPE_NOT_ARMED = "YELLOW_MOLTBOOK_ENVELOPE_NOT_ARMED"
    YELLOW_QUOTA_ZERO = "YELLOW_LIVE_POST_QUOTA_ZERO"
    YELLOW_NOT_STARTED = "YELLOW_REAL_SOAK_NOT_STARTED"
    YELLOW_PROOF_DELAYED = "YELLOW_PLATFORM_PROOF_DELAYED"
    RED_PUBLISH_DEFAULT = "RED_REAL_SOAK_LAUNCH_PUBLISHES_BY_DEFAULT"
    RED_NO_ENVELOPE = "RED_MOLTBOOK_POST_ALLOWED_WITHOUT_ENVELOPE"
    RED_UNBOUNDED_POSTS = "RED_ENVELOPE_ALLOWS_UNBOUNDED_POSTS"
    RED_UNBOUNDED_TIME = "RED_ENVELOPE_ALLOWS_UNBOUNDED_TIME_WINDOW"
    RED_EXPAND_ENVELOPE = "RED_ZERO_CAN_EXPAND_ENVELOPE"
    RED_INCREASE_QUOTA = "RED_ZERO_CAN_INCREASE_QUOTA"
    RED_CHANGE_PLATFORM = "RED_ZERO_CAN_CHANGE_PLATFORM"
    RED_CHANGE_COMMUNITY = "RED_ZERO_CAN_CHANGE_COMMUNITY"
    RED_NO_CANDIDATE = "RED_LIVE_POST_WITHOUT_CANDIDATE_RECEIPT"
    RED_NO_PERMIT = "RED_LIVE_POST_WITHOUT_PERMIT_RECEIPT"
    RED_NO_DISPATCH = "RED_LIVE_POST_WITHOUT_DISPATCH_RECEIPT"
    RED_NO_PROOF = "RED_LIVE_POST_WITHOUT_PLATFORM_PROOF"
    RED_NO_LEDGER = "RED_LIVE_POST_WITHOUT_LEDGER_ENTRY"
    RED_DRY_AS_LIVE = "RED_DRY_RUN_TREATED_AS_LIVE_POST"
    RED_PROOF_GREEN = "RED_PLATFORM_PROOF_MISSING_TREATED_GREEN"
    RED_CONTENT_MISMATCH = "RED_PLATFORM_PROOF_CONTENT_MISMATCH"
    RED_MASS_MESSAGE = "RED_MASS_MESSAGE_PATH"
    RED_FORBIDDEN_ACTION = "RED_REPLY_COMMENT_SEND_BROWSER_HARDWARE_PATH"
    RED_STOP = "RED_STOP_IGNORED"
    RED_PANIC = "RED_PANIC_IGNORED"


def now_iso() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).isoformat()


def new_id(prefix: str) -> str:
    return f"{prefix}-{uuid.uuid4().hex[:16]}"


def load_launch_policy() -> dict[str, Any]:
    if not POLICY_PATH.is_file():
        return {}
    return json.loads(POLICY_PATH.read_text(encoding="utf-8"))


def soak_dir(soak_id: str, *, base: Path | None = None) -> Path:
    root = base or STORE_ROOT
    return root / soak_id
