"""ALOOP-LIVE fixtures — deterministic autonomous loop supervisor bundles."""

from __future__ import annotations

from typing import Any

from hg_runtime.live_autonomous_loop.types import FIXTURE_CLOCK

FUTURE_EXPIRY = "2026-06-15T12:00:00.000000Z"
PAST_EXPIRY = "2026-06-13T12:00:00.000000Z"
FUTURE_LEASE = "2026-06-15T18:00:00.000000Z"
PAST_LEASE = "2026-06-13T18:00:00.000000Z"

ALOOP_FIXTURE_BUNDLES: tuple[dict[str, Any], ...] = (
    {
        "bundle_id": "aloop-valid-supervise",
        "notes": "valid loop supervisor lease path",
        "loop_request": {
            "request_id": "aloop-req-valid-supervise",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:valid-supervise",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-missing-operator-approval",
        "notes": "missing operator approval refusal",
        "loop_request": {
            "request_id": "aloop-req-missing-approval",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": None,
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:missing-approval",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-stale-approval",
        "notes": "stale approval refusal",
        "loop_request": {
            "request_id": "aloop-req-stale-approval",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": PAST_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:stale-approval",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-missing-iam",
        "notes": "missing IAM refusal",
        "loop_request": {
            "request_id": "aloop-req-missing-iam",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "bob",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:missing-iam",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-missing-tim",
        "notes": "missing TIM freshness refusal",
        "loop_request": {
            "request_id": "aloop-req-missing-tim",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:missing",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:missing-tim",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-missing-gpp",
        "notes": "missing GPP permit refusal where required",
        "loop_request": {
            "request_id": "aloop-req-missing-gpp",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "requires_gpp": True,
            "rollback_plan_ref": "rollback:plan:missing-gpp",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-missing-ueak",
        "notes": "missing UEAK admission refusal where required",
        "loop_request": {
            "request_id": "aloop-req-missing-ueak",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "requires_ueak": True,
            "rollback_plan_ref": "rollback:plan:missing-ueak",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-lease-expired",
        "notes": "expired lease refusal",
        "loop_request": {
            "request_id": "aloop-req-lease-expired",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": PAST_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:lease-expired",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-heartbeat-stale",
        "notes": "stale heartbeat refusal",
        "loop_request": {
            "request_id": "aloop-req-heartbeat-stale",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:stale",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:heartbeat-stale",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-budget-exceeded",
        "notes": "budget exceeded refusal",
        "loop_request": {
            "request_id": "aloop-req-budget-exceeded",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:exceeded",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:budget-exceeded",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-kill-switch",
        "notes": "kill switch engaged refusal",
        "loop_request": {
            "request_id": "aloop-req-kill-switch",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "kill_switch_engaged": True,
            "rollback_plan_ref": "rollback:plan:kill-switch",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-panic-lockdown",
        "notes": "panic lockdown refusal",
        "loop_request": {
            "request_id": "aloop-req-panic-lockdown",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "panic_lockdown": True,
            "rollback_plan_ref": "rollback:plan:panic-lockdown",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-self-renewal",
        "notes": "self-renewal refusal",
        "adversarial_signal": "self_renewal",
        "loop_request": {
            "request_id": "aloop-req-self-renewal",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "self_renewal_requested": True,
            "rollback_plan_ref": "rollback:plan:self-renewal",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-authority-conversion",
        "notes": "authority conversion refusal",
        "adversarial_signal": "authority_conversion",
        "loop_request": {
            "request_id": "aloop-req-authority-conversion",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "treat_as_authority": True,
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-secret-leak",
        "notes": "secret redaction refusal",
        "adversarial_signal": "secret_leak",
        "loop_request": {
            "request_id": "aloop-req-secret",
            "loop_scope": "password=secret123",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-pause-requested",
        "notes": "pause recorded without live loop start",
        "loop_request": {
            "request_id": "aloop-req-pause",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "pause_requested": True,
            "rollback_plan_ref": "rollback:plan:pause",
            "observed_at": FIXTURE_CLOCK,
        },
    },
    {
        "bundle_id": "aloop-valid-rollback",
        "notes": "valid rollback after fake-sink supervise",
        "loop_request": {
            "request_id": "aloop-req-valid-rollback",
            "loop_scope": "loop:fixture:observe",
            "lease_expires_at": FUTURE_LEASE,
            "heartbeat_ref": "hrt:heartbeat:fresh",
            "budget_ref": "budget:fixture:ok",
            "operator_ref": "op:local",
            "freshness_ref": "tim:approval_window_ok",
            "approval_expires_at": FUTURE_EXPIRY,
            "scope": "approve_change",
            "rollback_plan_ref": "rollback:plan:valid-rollback",
            "observed_at": FIXTURE_CLOCK,
        },
    },
)


def load_aloop_fixtures() -> tuple[dict[str, Any], ...]:
    return ALOOP_FIXTURE_BUNDLES


__all__ = [
    "ALOOP_FIXTURE_BUNDLES",
    "FUTURE_EXPIRY",
    "FUTURE_LEASE",
    "PAST_EXPIRY",
    "PAST_LEASE",
    "load_aloop_fixtures",
]
