"""HAL event type constants."""

from __future__ import annotations

HAL_REQUEST_RECEIVED = "HAL_REQUEST_RECEIVED"
HAL_CONTEXT_BUILT = "HAL_CONTEXT_BUILT"
HAL_ARBITRATION_STARTED = "HAL_ARBITRATION_STARTED"
HAL_DECISION_PROPOSED = "HAL_DECISION_PROPOSED"
HAL_ROUTE_SELECTED = "HAL_ROUTE_SELECTED"
HAL_GPP_ROUTE_REQUESTED = "HAL_GPP_ROUTE_REQUESTED"
HAL_UEAK_ROUTE_REQUESTED = "HAL_UEAK_ROUTE_REQUESTED"
HAL_OPERATOR_REVIEW_REQUESTED = "HAL_OPERATOR_REVIEW_REQUESTED"
HAL_REJECTED = "HAL_REJECTED"
HAL_FAILED_CLOSED = "HAL_FAILED_CLOSED"
HAL_PANIC_ENTERED = "HAL_PANIC_ENTERED"
HAL_DEGRADED_MODE_ENTERED = "HAL_DEGRADED_MODE_ENTERED"
HAL_REPLAY_VERIFIED = "HAL_REPLAY_VERIFIED"
HAL_AUTHORITY_CONVERSION_CONTAINED = "HAL_AUTHORITY_CONVERSION_CONTAINED"

ALL_EVENT_TYPES = frozenset(
    {
        HAL_REQUEST_RECEIVED,
        HAL_CONTEXT_BUILT,
        HAL_ARBITRATION_STARTED,
        HAL_DECISION_PROPOSED,
        HAL_ROUTE_SELECTED,
        HAL_GPP_ROUTE_REQUESTED,
        HAL_UEAK_ROUTE_REQUESTED,
        HAL_OPERATOR_REVIEW_REQUESTED,
        HAL_REJECTED,
        HAL_FAILED_CLOSED,
        HAL_PANIC_ENTERED,
        HAL_DEGRADED_MODE_ENTERED,
        HAL_REPLAY_VERIFIED,
        HAL_AUTHORITY_CONVERSION_CONTAINED,
    }
)

__all__ = [
    "ALL_EVENT_TYPES",
    "HAL_ARBITRATION_STARTED",
    "HAL_AUTHORITY_CONVERSION_CONTAINED",
    "HAL_CONTEXT_BUILT",
    "HAL_DECISION_PROPOSED",
    "HAL_DEGRADED_MODE_ENTERED",
    "HAL_FAILED_CLOSED",
    "HAL_GPP_ROUTE_REQUESTED",
    "HAL_OPERATOR_REVIEW_REQUESTED",
    "HAL_PANIC_ENTERED",
    "HAL_REJECTED",
    "HAL_REPLAY_VERIFIED",
    "HAL_REQUEST_RECEIVED",
    "HAL_ROUTE_SELECTED",
    "HAL_UEAK_ROUTE_REQUESTED",
]
