"""SOAR event type constants."""

from __future__ import annotations

SOAR_REQUEST_RECEIVED = "SOAR_REQUEST_RECEIVED"
SOAR_BUNDLE_BUILT = "SOAR_BUNDLE_BUILT"
SOAR_DOMAIN_SIGNAL_RECORDED = "SOAR_DOMAIN_SIGNAL_RECORDED"
SOAR_D7_COLLAPSE_RECORDED = "SOAR_D7_COLLAPSE_RECORDED"
SOAR_CRITIQUE_APPLIED = "SOAR_CRITIQUE_APPLIED"
SOAR_DECISION_RECORDED = "SOAR_DECISION_RECORDED"
SOAR_ROUTE_SELECTED = "SOAR_ROUTE_SELECTED"
SOAR_HAL_ROUTE_REQUESTED = "SOAR_HAL_ROUTE_REQUESTED"
SOAR_GPP_ROUTE_FIXTURE = "SOAR_GPP_ROUTE_FIXTURE"
SOAR_UEAK_ROUTE_FIXTURE = "SOAR_UEAK_ROUTE_FIXTURE"
SOAR_SOVEREIGN_REFUSAL = "SOAR_SOVEREIGN_REFUSAL"
SOAR_FAILED_CLOSED = "SOAR_FAILED_CLOSED"
SOAR_REPLAY_VERIFIED = "SOAR_REPLAY_VERIFIED"
SOAR_AUTHORITY_CONVERSION_CONTAINED = "SOAR_AUTHORITY_CONVERSION_CONTAINED"

ALL_EVENT_TYPES = frozenset(
    {
        SOAR_REQUEST_RECEIVED,
        SOAR_BUNDLE_BUILT,
        SOAR_DOMAIN_SIGNAL_RECORDED,
        SOAR_D7_COLLAPSE_RECORDED,
        SOAR_CRITIQUE_APPLIED,
        SOAR_DECISION_RECORDED,
        SOAR_ROUTE_SELECTED,
        SOAR_HAL_ROUTE_REQUESTED,
        SOAR_GPP_ROUTE_FIXTURE,
        SOAR_UEAK_ROUTE_FIXTURE,
        SOAR_SOVEREIGN_REFUSAL,
        SOAR_FAILED_CLOSED,
        SOAR_REPLAY_VERIFIED,
        SOAR_AUTHORITY_CONVERSION_CONTAINED,
    }
)

__all__ = [
    "ALL_EVENT_TYPES",
    "SOAR_AUTHORITY_CONVERSION_CONTAINED",
    "SOAR_BUNDLE_BUILT",
    "SOAR_CRITIQUE_APPLIED",
    "SOAR_D7_COLLAPSE_RECORDED",
    "SOAR_DECISION_RECORDED",
    "SOAR_DOMAIN_SIGNAL_RECORDED",
    "SOAR_FAILED_CLOSED",
    "SOAR_GPP_ROUTE_FIXTURE",
    "SOAR_HAL_ROUTE_REQUESTED",
    "SOAR_REPLAY_VERIFIED",
    "SOAR_REQUEST_RECEIVED",
    "SOAR_ROUTE_SELECTED",
    "SOAR_SOVEREIGN_REFUSAL",
    "SOAR_UEAK_ROUTE_FIXTURE",
]
